# Permalinks
permalink:           pretty

# Setup
title:               A
tagline:             Mess around
url:                 
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Auke van Veen
  url:               http://aukevanveen.com
  email:             aukevanveen@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/neveskiet/neveskiet.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
